package ui

import (
	"testing"

	"github.com/asheshgoplani/agent-deck/internal/session"
)

// TestPadToCells confirms plain-space padding to the target and the no-op
// path when content already meets or exceeds it.
func TestPadToCells(t *testing.T) {
	if got := padToCells("ab", 2, 5); got != "ab   " {
		t.Fatalf("padToCells(ab,2,5) = %q, want %q", got, "ab   ")
	}
	if got := padToCells("abcde", 5, 3); got != "abcde" {
		t.Fatalf("padToCells should be a no-op when wider than target, got %q", got)
	}
}

// TestPrimaryLabelFor_Precedence locks the dynamic-precedence identity
// engine the user approved: custom name > distinguishing branch >
// folder/worktree > Claude broadcast > auto name.
func TestPrimaryLabelFor_Precedence(t *testing.T) {
	cases := []struct {
		name        string
		inst        *session.Instance
		st          sessionRenderState
		branchCount map[string]int
		wantText    string
		wantKind    primaryKind
	}{
		{
			name:     "custom name beats everything",
			inst:     &session.Instance{Title: "CONDUCTOR", ProjectPath: "/x/MAIA.worker-3"},
			st:       sessionRenderState{branch: "ck/MAIA-1963-foo"},
			wantText: "CONDUCTOR",
			wantKind: primaryName,
		},
		{
			name:        "worker: unique branch wins over auto name, convention stripped",
			inst:        &session.Instance{Title: "prairie-condor", ProjectPath: "/x/MAIA.worker-3"},
			st:          sessionRenderState{branch: "ck/MAIA-1963-register-layer"},
			branchCount: map[string]int{"ck/MAIA-1963-register-layer": 1},
			wantText:    "1963-register-layer",
			wantKind:    primaryBranch,
		},
		{
			name:        "ro-dev: shared branch demotes to folder",
			inst:        &session.Instance{Title: "scarlet-meadow", ProjectPath: "/x/MAIA.ro-dev-2"},
			st:          sessionRenderState{branch: "shared-dev"},
			branchCount: map[string]int{"shared-dev": 3},
			wantText:    "ro-dev-2",
			wantKind:    primaryFolder,
		},
		{
			name:     "base branch is non-distinguishing -> folder",
			inst:     &session.Instance{Title: "light-thorn", ProjectPath: "/x/MAIA.worker-8"},
			st:       sessionRenderState{branch: "main"},
			wantText: "worker-8",
			wantKind: primaryFolder,
		},
		{
			name:     "no branch, no folder -> broadcast",
			inst:     &session.Instance{Title: "shadow-yarrow"},
			st:       sessionRenderState{paneTitle: "Editing config.go"},
			wantText: "Editing config.go",
			wantKind: primaryBroadcast,
		},
		{
			name:     "nothing else -> auto name as last resort",
			inst:     &session.Instance{Title: "shadow-yarrow"},
			st:       sessionRenderState{},
			wantText: "shadow-yarrow",
			wantKind: primaryAuto,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := primaryLabelFor(tc.inst, tc.st, tc.branchCount)
			if got.text != tc.wantText || got.kind != tc.wantKind {
				t.Fatalf("got {%q, %d}, want {%q, %d}", got.text, got.kind, tc.wantText, tc.wantKind)
			}
		})
	}
}

// TestIsAutoGeneratedName guards the meaningful-vs-disposable title split
// that decides whether a name outranks branch/worktree.
func TestIsAutoGeneratedName(t *testing.T) {
	auto := []string{"prairie-condor", "light-thorn", "scarlet-meadow", "shadow-yarrow", "amber-fox-1717000000"}
	for _, n := range auto {
		if !session.IsAutoGeneratedName(n) {
			t.Errorf("%q should be detected as auto-generated", n)
		}
	}
	custom := []string{"CONDUCTOR", "dev", "o", "agent-deck", "fix-the-bug", "amber-notaword"}
	for _, n := range custom {
		if session.IsAutoGeneratedName(n) {
			t.Errorf("%q should NOT be detected as auto-generated", n)
		}
	}
}
